### ISSUE TITLE
IntegerToBinary causes KeyError when no integer variables present

### ISSUE THREAD

**Issue by adekusar-drl** [stefan-woerner/qiskit-aqua#107]
### What is the current behavior?
Key error when an QP does not have integer variables.

### Steps to reproduce the problem
Run script:
```
from docplex.mp.model import Model

from qiskit.optimization import QuadraticProgram
from qiskit.optimization.converters import IntegerToBinary

if __name__ == '__main__':
    mdl = Model('quad-constraints')

    v = mdl.binary_var(name='v')
    w = mdl.continuous_var(name='w', lb=0.)

    mdl.minimize(v + w)
    mdl.add_constraint(v + w >= 1, "cons2")
    mdl.add_constraint(v ** 2 + w ** 2 <= 1, "cons2")

    op = QuadraticProgram()
    op.from_docplex(mdl)

    converter = IntegerToBinary()
    op = converter.encode(op)
```
Ouput:
```
Traceback (most recent call last):
  File "...run_int_to_bin.py", line 21, in <module>
    op = converter.encode(op)
  File "...qiskit-aqua/qiskit/optimization/converters/integer_to_binary.py", line 94, in encode
    self._substitute_int_var()
  File "...qiskit-aqua/qiskit/optimization/converters/integer_to_binary.py", line 186, in _substitute_int_var
    self._encode_quadratic_coefficients_dict(constraint.quadratic.to_dict())
  File "...qiskit-aqua/qiskit/optimization/converters/integer_to_binary.py", line 127, in _encode_quadratic_coefficients_dict
    x = self._src.get_variable(name_i)
  File "...qiskit-aqua/qiskit/optimization/problems/quadratic_program.py", line 234, in get_variable
    return self.variables[self._variables_index[i]]
KeyError: 0
```

For some reasons integer index has type of `intc` and in this snippet:
```
        if isinstance(i, int):
            return self.variables[i]
        else:
            return self.variables[self._variables_index[i]]
```
works `else` statement instead of `if`.

### What is the expected behavior?
The converter should do nothing in this case

**Comment by stefan-woerner** [comment]
Fixed in latest version.
